version: "3.8"
services:
  app :
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 60s
      retries: 10